### ISSUE TITLE
Error opening APS 8bmb files

### ISSUE THREAD

**Issue by lisavanloon** [nsherry4/Peakaboo#165]
Hi Nathaniel,

We seem to be having an issue opening full-sized (201 x 81 pixel) data files. We can open smaller ones. I've attached the error message
![APS 8bmb file opening error](https://user-images.githubusercontent.com/39059670/54442093-ff99e980-470b-11e9-96c1-9c8f21c43bb6.png)

**Comment by nsherry4** [comment]
Resolved with update to plugin. X/Y axes were reversed when looking up data from the HDF5 file.
