### ISSUE TITLE
xraylib: now on maven central

### ISSUE THREAD

**Issue by tschoonj** [nsherry4/Peakaboo#207]
Hi @nsherry4,

I am wrapping up development of a new xraylib release, and have recently put a lot of work in the Java implementation that you are using. One of my improvements is creating proper sources and javadoc jars, and managed to get them available on [Maven Central](https://search.maven.org/artifact/com.github.tschoonj/xraylib/3.99.2/jar).

I was wondering if you could give this a try and confirm that this is all working properly... It does here but confirmation would be nice :-)

Many thanks in advance,

Tom

**Comment by nsherry4** [comment]
This is great! I was able to switch over to the maven central version, and aside from changing an `XrayLibException` to an `IllegalArguementException`, everything just worked.

Am I correct in assuming that the version string `3.99.2` refers to a pre-release of `4.0`?

**Comment by tschoonj** [comment]
Glad that you like it.

Your assumption is correct. I expect to make a final 4.0.0 release around Christmas.

**Comment by tschoonj** [comment]
4.0.0 is out now, and is available from Maven Central

**Comment by nsherry4** [comment]
Thanks for getting this set up. Peakaboo is now switched over fo 4.0.0 in Maven and will be using it in it's next release.
